### ISSUE TITLE
 Integrate SQLite Database for Plate Storage

### ISSUE THREAD

**Issue by ertugrulmalkoc** [cydiann/realtimeplatedetection#5]
### Issue 5: Integrate SQLite Database for Plate Storage
**Title**: Integrate SQLite Database for Plate Storage

**Description**:
We need to store the detected car plate data in an SQLite database in addition to the JSON file. This will allow for more efficient querying and data management.

**Tasks**:
- [ ] Set up SQLite database in the project.
- [ ] Define the database schema for storing plate data.
- [ ] Write functions to insert detected plate data into the database.
- [ ] Write functions to query the database for plate data.
- [ ] Update the car plate detection module to store data in both JSON format and the SQLite database.

**Labels**: enhancement, database
